#create by winton wang
#email: wiwang@foxmail.com
version: "3.2"
services: 
  master:
    image: mysql:8.0
    container_name: master
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      # MYSQL_DATABASE: test
      # MYSQL_USER: slave
      # MYSQL_PASSWORD: 666666
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/conf:/etc/mysql/conf.d
  slave:
    image: mysql:8.0
    container_name: slave
    depends_on: 
      - master
    ports:
      - 3307:3306
      - 33070:33060
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./slave/data:/var/lib/mysql
      - ./slave/conf:/etc/mysql/conf.d