#create by winton wang
#email: wiwang@foxmail.com
version: "3.2"
services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
  redis:
    image: redis:5.0
    container_name: redis-server
    ports:
      - 6379:6379
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    volumes:
      - ./redis/conf:/usr/local/etc/redis
      - ./redis/data:/data
  mongo:
    image: mongo:4.0
    container_name: mongo
    ports:
      - 27017:27017
    # command: ['mongod', '--config', '/etc/mongo/mongod.conf']
    # volumes:
    #   - ./mongo/conf:/etc/mongo
    #   - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456